#!/usr/bin/with-contenv /bin/bash

ADDITION=0

if [[ "${RANDOM_MAX}" != '0' ]]; then
  ADDITION=$(( ( $RANDOM % ( $RANDOM_MAX - $RANDOM_MIN ) ) + $RANDOM_MIN ))
fi

TOTAL=$(( $ADDITION + $LIFESPAN ))

echo "[SUICIDE] Total lifespan ${TOTAL}secs, with ${ADDITION}secs randomness"

sleep $TOTAL

exit 1
