#!/bin/bash

_term() {
  echo "[SHUTDOWN] Interrupted, exiting..."
  exit $EXIT_CODE;
}

trap _term SIGTERM SIGINT

# Start nginx, in the background
echo "[STARTUP] Starting nginx on port ${CONTAINER_PORT}"
nginx

ADDITION=0

if [[ "${RANDOM_MAX}" != '0' ]]; then
  ADDITION=$(( ( $RANDOM % ( $RANDOM_MAX - $RANDOM_MIN ) ) + $RANDOM_MIN ))
fi

TOTAL=$(( $ADDITION + $LIFESPAN ))

echo "[STARTUP] Total lifespan ${TOTAL}secs, with ${ADDITION}secs randomness"
echo "[STARTUP] Will exit with code ${EXIT_CODE}"

sleep $TOTAL

echo "[SHUTDOWN] Lifespan expired, goodbye"
exit $EXIT_CODE
